"""Emit the Replica 2x2 tables (BAL x contest) as LaTeX: global macro and per scene."""
import argparse
import glob
import re
from pathlib import Path

import numpy as np

NUM = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
       6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten"}

from ovo.utils.results_utils import parse_instance_ap_file, parse_statistics_file

SCENES = ["office0", "office1", "office2", "office3", "office4", "room0", "room1", "room2"]
# label -> (folder tag, uid prefix); order matches the 2x2 reading: base, each mechanism, both
CELLS = [
    ("base",                  "base",         "rb"),
    ("base + contest",        "base-contest", "rc"),
    ("base + BAL",            "base-BAL",     "rbb"),
    ("base + contest + BAL",  "BAL-contest",  "rcb"),
]
KEYS = ["mIoU", "mAcc", "AP", "AP50", "AP25"]
_AP = {"AP": "AP_agnostic", "AP50": "AP_agnostic_50", "AP25": "AP_agnostic_25"}


def cell_runs(out_dir: Path, tag: str, prefix: str) -> list[Path]:
    """Run folders of one cell. `rb` also prefixes `rbb`, hence the exact uid match."""
    return [Path(p) for p in sorted(glob.glob(str(out_dir / f"*replica-2x2-{tag}_{prefix}[0-9]*")))
            if re.fullmatch(rf"{prefix}\d+", Path(p).name.rsplit("_", 1)[-1])]


def scene_metrics(run: Path, scene: str) -> dict | None:
    stats = parse_statistics_file(run / "replica" / f"statistics_{scene}.txt")
    if stats is None:
        return None
    ap = parse_instance_ap_file(run / "replica" / f"instance_ap_{scene}.txt") or {}
    out = {"mIoU": 100 * stats["mIoU"], "mAcc": 100 * stats["mAcc"]}
    out.update({k: 100 * ap.get(v, np.nan) for k, v in _AP.items()})
    return out


def collect(out_dir: Path) -> dict:
    """{cell: {scene: [per-run metrics]}}."""
    return {cell: {s: [m for r in cell_runs(out_dir, tag, pre) if (m := scene_metrics(r, s))]
                   for s in SCENES}
            for cell, tag, pre in CELLS}


def cell_text(values: np.ndarray, best: float | None = None) -> str:
    """mean +/- std, or a dash when nothing was found.

    `best` is the winning mean of that column; the mean is set in bold when it matches, on the
    rounded value so that 30.44 and 30.48 do not tie despite printing 30.4 and 30.5.
    """
    values = np.asarray(values, dtype=float)
    if values.size == 0 or np.all(np.isnan(values)):
        return "--"
    mean = np.nanmean(values)
    txt = f"{mean:.1f}"
    if best is not None and round(mean, 1) == round(best, 1):
        txt = f"\\textbf{{{txt}}}"
    if values.size < 2:
        return txt
    return f"{txt} {{\\scriptsize $\\pm$ {np.nanstd(values, ddof=1):.1f}}}"


def _header(scene_col: str) -> str:
    return (r"""  \begin{tabular}{ll cc c ccc}
    \toprule
    & & \multicolumn{2}{c}{Semantic} & &
      \multicolumn{3}{c}{AP class-agnostic} \\
    \cmidrule(lr){3-4}\cmidrule(lr){6-8}
    """ + scene_col + r""" & Configuration & mIoU & mAcc & & AP & AP$_{50}$ & AP$_{25}$ \\
    \midrule""")


def emit_global(data: dict) -> str:
    """One row per cell. Each run is first averaged over the eight scenes, so the reported
    spread is the run-to-run one (ORB-SLAM2 is non-deterministic) and not the much larger
    spread between scenes, which only says that office4 scores higher than office1."""
    macro_all = {}
    for cell, _, _ in CELLS:
        n_runs = min(len(data[cell][s]) for s in SCENES)
        macro_all[cell] = {k: np.array([np.nanmean([data[cell][s][i][k] for s in SCENES])
                                        for i in range(n_runs)]) for k in KEYS}
    best = {k: max(np.nanmean(macro_all[c][k]) for c, _, _ in CELLS) for k in KEYS}
    body = ""
    for cell, _, _ in CELLS:
        macro = macro_all[cell]
        name = f"\\textbf{{{cell}}}" if cell == "base + contest + BAL" else cell
        if cell == "base + contest + BAL":
            body += "    \\rowcolor{gray!12}\n"
        cols = (" & ".join(cell_text(macro[k], best[k]) for k in KEYS[:2]) + " & & "
                + " & ".join(cell_text(macro[k], best[k]) for k in KEYS[2:]))
        body += f"    {name} & {cols} \\\\\n"
    n = min(len(data[c][s]) for c, _, _ in CELLS for s in SCENES)
    note = (f"Mean $\\pm$ std over {NUM.get(n, n)} runs per condition; each run is averaged over "
            f"the {NUM[len(SCENES)]} scenes first.")
    return f"""% GENERATED by studies/geo_2x2_replica_table.py -- do not edit by hand.
% Replica, {len(SCENES)} scenes, {n} runs per cell.
% \\input{{figures/tab_geo_2x2_replica}}
\\begin{{table}}[ht]
  \\centering
  \\setlength{{\\tabcolsep}}{{5pt}}
  \\renewcommand{{\\arraystretch}}{{1.15}}
  \\resizebox{{\\textwidth}}{{!}}{{%
  \\begin{{tabular}}{{@{{}}l cc c ccc@{{}}}}
    \\toprule
    Configuration & mIoU (\\%) & mAcc (\\%) & & AP (\\%) & AP$_{{50}}$ (\\%) & AP$_{{25}}$ (\\%) \\\\
    \\midrule
{body}    \\bottomrule
  \\end{{tabular}}%
  }}
  \\par\\vspace{{2pt}}
  \\makebox[\\textwidth][l]{{\\footnotesize\\itshape {note}}}
  \\caption{{Geometric refresh (BAL) and contest, crossed, on the {NUM[len(SCENES)]} Replica
    scenes, on ORB-SLAM2 with loop closures.}}
  \\label{{tab:geo_2x2_replica}}
\\end{{table}}
"""


def emit_per_scene(data: dict) -> str:
    """One block per scene, four rows each: mean +/- std over the repeated runs."""
    body = ""
    for i, scene in enumerate(SCENES):
        if i:
            body += "    \\midrule\n"
        best = {k: max(np.nanmean([m[k] for m in data[c][scene]]) for c, _, _ in CELLS)
                for k in KEYS}
        for j, (cell, _, _) in enumerate(CELLS):
            runs = data[cell][scene]
            label = f"\\texttt{{{scene}}}" if j == 0 else ""
            vals = {k: np.array([m[k] for m in runs]) for k in KEYS}
            cols = (" & ".join(cell_text(vals[k], best[k]) for k in KEYS[:2]) + " & & "
                    + " & ".join(cell_text(vals[k], best[k]) for k in KEYS[2:]))
            body += f"    {label} & {cell} & {cols} \\\\\n"
    n = min(len(data[c][s]) for c, _, _ in CELLS for s in SCENES)
    note = f"Mean $\\pm$ std over {NUM.get(n, n)} runs per condition."
    return f"""% GENERATED by studies/geo_2x2_replica_table.py -- do not edit by hand.
% \\input{{figures/tab_geo_2x2_replica_scenes}}
\\begin{{table}}[ht]
  \\centering
  \\setlength{{\\tabcolsep}}{{5pt}}
  \\renewcommand{{\\arraystretch}}{{1.05}}
  \\resizebox{{\\textwidth}}{{!}}{{%
  \\begin{{tabular}}{{@{{}}ll cc c ccc@{{}}}}
    \\toprule
    Scene & Configuration & mIoU (\\%) & mAcc (\\%) & & AP (\\%) & AP$_{{50}}$ (\\%) & AP$_{{25}}$ (\\%) \\\\
    \\midrule
{body}    \\bottomrule
  \\end{{tabular}}%
  }}
  \\par\\vspace{{2pt}}
  \\makebox[\\textwidth][l]{{\\footnotesize\\itshape {note}}}
  \\caption{{Geometric refresh (BAL) and contest, crossed, scene by scene on Replica.}}
  \\label{{tab:geo_2x2_replica_scenes}}
\\end{{table}}
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", default="data/output/Replica")
    ap.add_argument("--figures", default="tfm/figures")
    args = ap.parse_args()
    data = collect(Path(args.out_dir))
    fig = Path(args.figures)
    (fig / "tab_geo_2x2_replica.tex").write_text(emit_global(data))
    (fig / "tab_geo_2x2_replica_scenes.tex").write_text(emit_per_scene(data))
    for cell, _, _ in CELLS:
        print(f"{cell:22s} {len(data[cell][SCENES[0]])} runs/scene")
    print(f"wrote {fig}/tab_geo_2x2_replica.tex and tab_geo_2x2_replica_scenes.tex")


if __name__ == "__main__":
    main()
