"""Emit the 2x2 geometric-consistency table (BAL x contest) as LaTeX from run folders."""
import argparse
import glob
import re
from pathlib import Path

import numpy as np

NUM = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
       6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten"}

from ovo.utils.results_utils import (
    parse_instance_ap_file,
    parse_instance_counts,
    parse_statistics_file,
)

# cell label -> (folder tag, uid prefix); uid = prefix + run number
CELLS = [
    ("base",                 "base",         "cb"),
    ("base + BAL",           "base-BAL",     "cbb"),
    ("base + contest",       "base-contest", "cc"),
    ("base + contest + BAL", "BAL-contest",  "ccb"),
]


def collect(out_dir: Path, scene: str, pattern: str) -> dict:
    """Gather per-run metrics for every cell. Returns {cell: list of metric dicts}."""
    rows = {}
    for cell, tag, prefix in CELLS:
        runs = []
        for d in sorted(glob.glob(str(out_dir / f"*{pattern}-{tag}_{prefix}[0-9]*"))):
            d = Path(d)
            # `cb` also prefixes `cbb`: keep only folders whose uid matches this cell exactly
            if not re.fullmatch(rf"{prefix}\d+", d.name.rsplit("_", 1)[-1]):
                continue
            stats = parse_statistics_file(d / "scannetv2" / f"statistics_{scene}.txt")
            if stats is None:
                continue
            ap = parse_instance_ap_file(d / "scannetv2" / f"instance_ap_{scene}.txt") or {}
            runs.append({
                "mIoU": 100 * stats["mIoU"],
                "mAcc": 100 * stats["mAcc"],
                "AP": 100 * ap.get("AP_agnostic", np.nan),
                "AP50": 100 * ap.get("AP_agnostic_50", np.nan),
                "AP25": 100 * ap.get("AP_agnostic_25", np.nan),
            })
        rows[cell] = runs
    return rows


def cell_text(runs: list, key: str, best: float | None = None) -> str:
    """mean +/- std over runs, or a dash when nothing was found.

    `best` is the winning mean of that column; the mean is set in bold when it matches, on the
    rounded value so that 30.44 and 30.48 do not tie despite printing 30.4 and 30.5.
    """
    if not runs:
        return "--"
    vals = np.array([r[key] for r in runs], dtype=float)
    if np.all(np.isnan(vals)):
        return "--"
    mean = np.nanmean(vals)
    txt = f"{mean:.1f}"
    if best is not None and round(mean, 1) == round(best, 1):
        txt = f"\\textbf{{{txt}}}"
    if len(vals) < 2:
        return txt
    return f"{txt} {{\\scriptsize $\\pm$ {np.nanstd(vals, ddof=1):.1f}}}"


def emit(rows: dict, scene: str, frame_limit: int) -> str:
    n_runs = {c: len(r) for c, r in rows.items()}
    scene_tex = scene.replace("_", r"\_")
    keys = ("mIoU", "mAcc", "AP", "AP50", "AP25")
    best = {k: max(np.nanmean([r[k] for r in rows[c]]) for c, _, _ in CELLS if rows[c])
            for k in keys}
    body = ""
    for cell, _, _ in CELLS:
        runs = rows[cell]
        name = f"\\textbf{{{cell}}}" if cell == "base + contest + BAL" else cell
        if cell == "base + contest + BAL":
            body += "    \\rowcolor{gray!12}\n"
        cols = (" & ".join(cell_text(runs, k, best[k]) for k in keys[:2]) + " & & "
                + " & ".join(cell_text(runs, k, best[k]) for k in keys[2:]))
        body += f"    {name} & {cols} \\\\\n"
    n = min(n_runs.values())
    note = f"Mean $\\pm$ std over {NUM.get(n, n)} runs per condition."
    return f"""% GENERATED by studies/geo_2x2_table.py -- do not edit by hand.
% Scene {scene}, first {frame_limit} frames. Runs per cell: {n_runs}.
% \\input{{figures/tab_geo_2x2}}
\\begin{{table}}[ht]
  \\centering
  \\setlength{{\\tabcolsep}}{{5pt}}
  \\renewcommand{{\\arraystretch}}{{1.15}}
  \\resizebox{{\\textwidth}}{{!}}{{%
  \\begin{{tabular}}{{@{{}}l cc c ccc@{{}}}}
    \\toprule
    Configuration & mIoU (\\%) & mAcc (\\%) & & AP (\\%) & AP$_{{50}}$ (\\%) & AP$_{{25}}$ (\\%) \\\\
    \\midrule
{body}    \\bottomrule
  \\end{{tabular}}%
  }}
  \\par\\vspace{{2pt}}
  \\makebox[\\textwidth][l]{{\\footnotesize\\itshape {note}}}
  \\caption{{Geometric refresh (BAL) and contest, crossed. ScanNet {scene_tex}, first
    {frame_limit} frames, on ORB-SLAM2 with loop closures.}}
  \\label{{tab:geo_2x2}}
\\end{{table}}
"""


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output-dir", default="data/output/ScanNet")
    p.add_argument("--scene", default="scene0011_00")
    p.add_argument("--pattern", default="cut2030", help="folder-name tag identifying the study")
    p.add_argument("--frame-limit", type=int, default=2030)
    p.add_argument("--out", default="tfm/figures/tab_geo_2x2.tex")
    args = p.parse_args()

    rows = collect(Path(args.output_dir), args.scene, args.pattern)
    Path(args.out).write_text(emit(rows, args.scene, args.frame_limit))
    for cell, runs in rows.items():
        print(f"  {cell:<22} {len(runs)} runs")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
